### ISSUE TITLE
#import "RCTBridgeModule.h" can't be found

### ISSUE THREAD

**Issue by myusuf3** [dsibiski/react-native-userdefaults-ios#4]
I npm installed the package as suggested in the `README.md` but for some reason when your project references `#import "RCTBridgeModule.h"` it can't seem to find it. 

![screen shot 2015-05-20 at 1 10 07 pm](https://cloud.githubusercontent.com/assets/156825/7732050/ea608eee-fef2-11e4-8873-c37fc7988b0b.png)

![screen shot 2015-05-20 at 1 23 07 pm](https://cloud.githubusercontent.com/assets/156825/7732128/710c974e-fef3-11e4-8d6c-ff32d3a93fc0.png)

**Comment by dsibiski** [comment]
@myusuf3 v0.0.4 should fix this issue.

When you update (and re-open your project in Xcode, make sure the following HEADER_SEARCH_PATHS are set:

![Screenshot](https://d1zjcuqflbd5k.cloudfront.net/files/acc_391911/qUo8?response-content-disposition=inline;%20filename=Screen%20Shot%202015-05-20%20at%2014.36.59.png&Expires=1432147173&Signature=a3FwSjFIpFQQypkdFfVIlFaQ7CX7zOoXxkOgyeC6SnYRSEANT6apkG~4z43Z2RAytRq0SrMNTt0-f1WXC-yMebtUHm58liJ8Rj242DstDk7fc3dpHtt~KikNXre-IGHXF9LEgu7V0Ha8n7pONquJENQ9ag4e3TWQPk3YvTt6qmg_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

If you still can't build, let me know how you created your project, I'm not aware of any other HEADER_SEARCH_PATHS that would need to be added...

Thanks!

**Comment by myusuf3** [comment]
Thanks will report back soon.

**Comment by myusuf3** [comment]
@dsibiski sorry dude been pretty busy. I am sure you got it. :100:

**Comment by dsibiski** [comment]
@myusuf3 Nah, no problem man. Thanks to you, I was able to fix this before more people started using it.  :+1:

**Comment by montosajo** [comment]
Hi,sounds weird but I found same problem now almost 1 year later than the report date .And the image for the headers is missing (403) .Maybe the HEADERS are the clue on this .Tks

**Comment by dsibiski** [comment]
@montosajo Strange, is your `react-native` in the `node_modules`?

Here is another image to show what the header search paths should be for the lib. It is basically saying, look up one level (which should be `node_modules`, since that is where the userdefaults lib should be), find `react-native/React` there and then look for headers there.

![](https://i.imgur.com/g9j5O48.png)

**Comment by montosajo** [comment]
Thanks .Really

I ll check & be back .
R
Giorgio

**Comment by montosajo** [comment]
Hi :
we do not see any diff and what is funny is that we use a bunch of
libraries coming from the public repository and many of them use the
'offending' #import "RCTBridgeModule.h" and they have similar header
definition  ,as indicated below
structure [image: Inline image 1]
this the h. for SpeechSynthesizer

[image: Inline image 2]

[image: Inline image 1]

[image: Inline image 2]

Regards
again thanks you from the heart of the cold pampas :)
Giorgio & Muka

**Comment by montosajo** [comment]
Addenda.
We tested this using react-native-cli: 0.1.10
react-native: 0.30.0
and a skinny project 
some status

and the headers are identical to the ones for a working module.
and
ls -al node_modules/react-native
total 88
drwxr-xr-x   19 giorgioborgia  staff    646 Aug  3 20:35 .
drwxr-xr-x  591 giorgioborgia  staff  20094 Aug  4 07:58 ..
-rw-r--r--    1 giorgioborgia  staff   1139 Jul 21 04:11 .flowconfig
-rw-r--r--    1 giorgioborgia  staff   1533 Jul 21 04:11 LICENSE
drwxr-xr-x   48 giorgioborgia  staff   1632 Aug  3 20:35 Libraries
-rw-r--r--    1 giorgioborgia  staff   1989 Jul 21 04:11 PATENTS
drwxr-xr-x    9 giorgioborgia  staff    306 Aug  3 20:35 React
-rw-r--r--    1 giorgioborgia  staff   4846 Jul 21 04:11 React.podspec
drwxr-xr-x   11 giorgioborgia  staff    374 Aug  3 20:35 ReactAndroid
drwxr-xr-x    3 giorgioborgia  staff    102 Jul 21 04:11 ReactCommon
drwxr-xr-x    3 giorgioborgia  staff    102 Jul 21 05:34 android
-rw-r--r--    1 giorgioborgia  staff    440 Jul 21 04:11 cli.js
drwxr-xr-x    6 giorgioborgia  staff    204 Aug  3 20:35 flow
drwxr-xr-x    4 giorgioborgia  staff    136 Aug  3 20:35 jestSupport
drwxr-xr-x   11 giorgioborgia  staff    374 Aug  3 20:35 lib
drwxr-xr-x   28 giorgioborgia  staff    952 Aug  3 20:35 local-cli
-rw-r--r--    1 giorgioborgia  staff   8500 Aug  3 20:35 package.json
drwxr-xr-x   13 giorgioborgia  staff    442 Aug  3 20:35 packager
-rw-r--r--    1 giorgioborgia  staff   4917 Jul 21 04:11 react.gradle

R

**Comment by dsibiski** [comment]
@montosajo Thanks! Would you be able to put that repo on GitHub so I can download it and see what's going on?

**Comment by montosajo** [comment]
Yes .In the next 2 hours as we have now a pow meeting :)

Thanks
Muka

**Comment by montosajo** [comment]
Here we go

https://github.com/montosajo/repotest

The usedefaults should be commented out @usage.js

and your project added to the project under Libraries and of course the .a
module should be added to the linked lib zone.

Without it the project is working 'as is '

Rgds

giorgio

**Comment by montosajo** [comment]
Hi,in the machine with 0.30 after
closing Xcode
cleaning all npm buffers
[praying a bit :)]
restarting the ios (yes shame a bit like in windows)

t_he missing #import resurrected !!_
So after some back and forth project is working

_Again,we want to thank you for your attention_

_Regards_

_Giorgio ,Muka and team_

PS :the project we are involved means to have a voice animated recipe (step
by step)
but :
using voice recognition OFFLINE (*)
text to voice 'reading'
storing the recipes in a sqllite db ,so u can create your own 'recipe' with
a shot-type-order and export
to share the recipe
use timers to control the process

As you will understand this is not limited to cooking recipes :)
(+) polipetix for places where wifi & internet is not available or allowed

**Comment by dsibiski** [comment]
@montosajo Great to hear!

**Comment by montosajo** [comment]
Sorry to ask,but your home town is in Puerto Rico ?
We do work a a lot with the  caribbean and Muka is from Suriname :)
Regards
G
